### ISSUE TITLE
Include links to our docs with the messages

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy-bot#4]
The messages from sunpy-bot may be scary to new contributors that haven't read the dev docs. The bot should be helpful enough to point them to the right place on our documentation so they don't think [they've broken something](https://medium.com/@_hawks_/chapter-0-the-prelude-320751d2e61e).

**Comment by Cadair** [comment]
This repo is now dead. All the config for giles is in the core repo's `pyproject.toml` file, we can add links there, although I think they are already configured.
